// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALhbbH_AKkLkoiHEf7VOKk8nrc2D25WvY',
    appId: '1:284576517158:web:9f2cfd2d7102d40a706ae7',
    messagingSenderId: '284576517158',
    projectId: 'smart-tutor-lite-a66b5',
    authDomain: 'smart-tutor-lite-a66b5.firebaseapp.com',
    storageBucket: 'smart-tutor-lite-a66b5.firebasestorage.app',
    measurementId: 'G-CSTP9MXW51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ0lBzuBTdk-Z9oISubLOKVp2U9UcND70',
    appId: '1:284576517158:android:3fe827fdde751511706ae7',
    messagingSenderId: '284576517158',
    projectId: 'smart-tutor-lite-a66b5',
    storageBucket: 'smart-tutor-lite-a66b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZpSGHjQSAwAMPp_nr3FExzmy44Z8jt_U',
    appId: '1:284576517158:ios:5b40d708677bf7d0706ae7',
    messagingSenderId: '284576517158',
    projectId: 'smart-tutor-lite-a66b5',
    storageBucket: 'smart-tutor-lite-a66b5.firebasestorage.app',
    iosBundleId: 'com.example.smartTutorLite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZpSGHjQSAwAMPp_nr3FExzmy44Z8jt_U',
    appId: '1:284576517158:ios:5b40d708677bf7d0706ae7',
    messagingSenderId: '284576517158',
    projectId: 'smart-tutor-lite-a66b5',
    storageBucket: 'smart-tutor-lite-a66b5.firebasestorage.app',
    iosBundleId: 'com.example.smartTutorLite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALhbbH_AKkLkoiHEf7VOKk8nrc2D25WvY',
    appId: '1:284576517158:web:a93403e61933e38c706ae7',
    messagingSenderId: '284576517158',
    projectId: 'smart-tutor-lite-a66b5',
    authDomain: 'smart-tutor-lite-a66b5.firebaseapp.com',
    storageBucket: 'smart-tutor-lite-a66b5.firebasestorage.app',
    measurementId: 'G-FPPHRW1ZK6',
  );

}