import 'dart:collection';

import 'package:equatable/equatable.dart';

/// Represents a transcription generated from an audio source.
class Transcription extends Equatable {
  const Transcription({
    required this.id,
    required this.text,
    required this.audioPath,
    required this.duration,
    required this.timestamp,
    required this.confidence,
    this.metadata = const <String, dynamic>{},
    this.title,
    this.structuredNote,
  });

  final String id;
  final String text;
  final String audioPath;
  final Duration duration;
  final DateTime timestamp;
  final double confidence;
  final Map<String, dynamic> metadata;
  
  /// Title of the note generated by ChatGPT (nullable for backward compatibility).
  final String? title;
  
  /// Structured note content (summary, key_points, action_items, study_questions)
  /// generated by ChatGPT (nullable for backward compatibility).
  final Map<String, dynamic>? structuredNote;

  /// Returns an unmodifiable view to keep the entity immutable.
  UnmodifiableMapView<String, dynamic> get metadataView =>
      UnmodifiableMapView(metadata);

  @override
  List<Object?> get props => [
        id,
        text,
        audioPath,
        duration,
        timestamp,
        confidence,
        metadata,
        title,
        structuredNote,
      ];
}
